import Foundation

struct TeamNameMap {
    static let mapping: [String: String] = [
        // ===== NBA (30 隊完整) =====
        "Atlanta Hawks": "亞特蘭大老鷹",
        "Boston Celtics": "波士頓塞爾提克",
        "Brooklyn Nets": "布魯克林籃網",
        "Charlotte Hornets": "夏洛特黃蜂",
        "Chicago Bulls": "芝加哥公牛",
        "Cleveland Cavaliers": "克里夫蘭騎士",
        "Dallas Mavericks": "達拉斯獨行俠",
        "Denver Nuggets": "丹佛金塊",
        "Detroit Pistons": "底特律活塞",
        "Golden State Warriors": "金州勇士",
        "Houston Rockets": "休士頓火箭",
        "Indiana Pacers": "印第安納溜馬",
        "Los Angeles Clippers": "洛杉磯快艇",
        "Los Angeles Lakers": "洛杉磯湖人",
        "Memphis Grizzlies": "曼菲斯灰熊",
        "Miami Heat": "邁阿密熱火",
        "Milwaukee Bucks": "密爾瓦基公鹿",
        "Minnesota Timberwolves": "明尼蘇達灰狼",
        "New Orleans Pelicans": "紐奧良鵜鶘",
        "New York Knicks": "紐約尼克",
        "Oklahoma City Thunder": "奧克拉荷馬雷霆",
        "Orlando Magic": "奧蘭多魔術",
        "Philadelphia 76ers": "費城七六人",
        "Phoenix Suns": "鳳凰城太陽",
        "Portland Trail Blazers": "波特蘭拓荒者",
        "Sacramento Kings": "沙加緬度國王",
        "San Antonio Spurs": "聖安東尼奧馬刺",
        "Toronto Raptors": "多倫多暴龍",
        "Utah Jazz": "猶他爵士",
        "Washington Wizards": "華盛頓巫師",
        
        // ===== MLB =====
        "New York Yankees": "紐約洋基",
        "Boston Red Sox": "波士頓紅襪",
        "Los Angeles Dodgers": "洛杉磯道奇",
        "Chicago Cubs": "芝加哥小熊",
        "Houston Astros": "休士頓太空人",
        "Arizona Diamondbacks": "亞利桑那響尾蛇",
        "Milwaukee Brewers": "密爾瓦基釀酒人",
        "Colorado Rockies": "科羅拉多落磯",
        "Kansas City Royals": "堪薩斯皇家",
        "Minnesota Twins": "明尼蘇達雙城",
        "Cincinnati Reds": "辛辛那提紅人",
        "St. Louis Cardinals": "聖路易紅雀",
        "Washington Nationals": "華盛頓國民",
        "Athletics": "奧克蘭運動家",
        "Cleveland Guardians": "克里夫蘭守護者",
        "Texas Rangers": "德州遊騎兵",
        "Los Angeles Angels": "洛杉磯天使",
        "New York Mets": "紐約大都會",
        "San Diego Padres": "聖地牙哥教士",
        "Tampa Bay Rays": "坦帕灣光芒",
        "Miami Marlins": "邁阿密馬林魚",
        "Chicago White Sox": "芝加哥白襪",
        "Philadelphia Phillies": "費城費城人",
        "Seattle Mariners": "西雅圖水手",
        "Detroit Tigers": "底特律老虎",
        "Baltimore Orioles": "巴爾的摩金鶯",
        "Toronto Blue Jays": "多倫多藍鳥",
        "San Francisco Giants": "舊金山巨人",
        "Pittsburgh Pirates": "匹茲堡海盜",
        "Atlanta Braves": "亞特蘭大勇士",
        
        // ===== NPB (日本職棒) =====
        // 中央聯盟 (Central League)
        "Yomiuri Giants": "讀賣巨人",
        "Hanshin Tigers": "阪神虎",
        "Chunichi Dragons": "中日龍",
        "Yokohama DeNA BayStars": "橫濱DeNA海灣之星",
        "Hiroshima Toyo Carp": "廣島東洋鯉魚",
        "Tokyo Yakult Swallows": "東京養樂多燕子",
        // 太平洋聯盟 (Pacific League)
        "Fukuoka SoftBank Hawks": "福岡軟銀鷹",
        "Orix Buffaloes": "歐力士猛牛",
        "ORIX Buffaloes": "歐力士猛牛",
        "Chiba Lotte Marines": "千葉羅德海洋",
        "Saitama Seibu Lions": "埼玉西武獅",
        "Tohoku Rakuten Golden Eagles": "東北樂天金鷲",
        "Hokkaido Nippon-Ham Fighters": "北海道日本火腿鬥士",
        
        // ===== CPBL (中華職棒) =====
        "Uni-President 7-Eleven Lions": "統一7-ELEVEn獅",
        "CTBC Brothers": "中信兄弟",
        "Fubon Guardians": "富邦悍將",
        "Rakuten Monkeys": "樂天桃猿",
        "Wei Chuan Dragons": "味全龍",
        "TSG Hawks": "台鋼雄鷹",
        
        // ===== FIFA / 世界盃足球 =====
        "Argentina": "阿根廷",
        "Brazil": "巴西",
        "France": "法國",
        "Germany": "德國",
        "Spain": "西班牙",
        "Portugal": "葡萄牙",
        "England": "英格蘭",
        "Netherlands": "荷蘭",
        "Belgium": "比利時",
        "Italy": "義大利",
        "Croatia": "克羅埃西亞",
        "Uruguay": "烏拉圭",
        "Morocco": "摩洛哥",
        "Japan": "日本",
        "South Korea": "南韓",
        "Senegal": "塞內加爾",
        "Switzerland": "瑞士",
        "United States": "美國",
        "Mexico": "墨西哥",
        "Denmark": "丹麥",
        "Poland": "波蘭",
        "Colombia": "哥倫比亞",
        "Chile": "智利",
        "Nigeria": "奈及利亞",
        "Cameroon": "喀麥隆",
        "Ghana": "迦納",
        "Ivory Coast": "象牙海岸",
        "Egypt": "埃及",
        "Tunisia": "突尼西亞",
        "Algeria": "阿爾及利亞",
        "Saudi Arabia": "沙烏地阿拉伯",
        "Iran": "伊朗",
        "Australia": "澳洲",
        "New Zealand": "紐西蘭",
        "Serbia": "塞爾維亞",
        "Sweden": "瑞典",
        "Norway": "挪威",
        "Wales": "威爾斯",
        "Czech Republic": "捷克",
        "Austria": "奧地利",
        "Hungary": "匈牙利",
        "Turkey": "土耳其",
        "Russia": "俄羅斯",
        "Ukraine": "烏克蘭",
        "Scotland": "蘇格蘭",
        "Canada": "加拿大",
        "Costa Rica": "哥斯大黎加",
        "Ecuador": "厄瓜多",
        "Peru": "秘魯",
        "Paraguay": "巴拉圭",
        "Venezuela": "委內瑞拉",
        "Jamaica": "牙買加",
        "Honduras": "宏都拉斯",
        "Panama": "巴拿馬",
        "Iceland": "冰島",
        "Slovakia": "斯洛伐克",
        "Slovenia": "斯洛維尼亞",
        "Romania": "羅馬尼亞",
        "Bulgaria": "保加利亞",
        "Greece": "希臘",
        "Finland": "芬蘭",
        "Republic of Ireland": "愛爾蘭",
        "Northern Ireland": "北愛爾蘭",
        "Bosnia and Herzegovina": "波士尼亞與赫塞哥維納",
        "Montenegro": "蒙特內哥羅",
        "North Macedonia": "北馬其頓",
        "Albania": "阿爾巴尼亞",
        "Georgia": "喬治亞",
        "Armenia": "亞美尼亞",
        "Kazakhstan": "哈薩克",
        "Uzbekistan": "烏茲別克",
        "Qatar": "卡達",
        "United Arab Emirates": "阿拉伯聯合大公國",
        "Oman": "阿曼",
        "Bahrain": "巴林",
        "Jordan": "約旦",
        "Iraq": "伊拉克",
        "Syria": "敘利亞",
        "Lebanon": "黎巴嫩",
        "Palestine": "巴勒斯坦",
        "Kuwait": "科威特",
        "Yemen": "葉門",
        "Thailand": "泰國",
        "Vietnam": "越南",
        "Indonesia": "印尼",
        "Malaysia": "馬來西亞",
        "Philippines": "菲律賓",
        "Singapore": "新加坡",
        "Myanmar": "緬甸",
        "Cambodia": "柬埔寨",
        "Laos": "寮國",
        "Mongolia": "蒙古",
        "India": "印度",
        "Pakistan": "巴基斯坦",
        "Bangladesh": "孟加拉",
        "Sri Lanka": "斯里蘭卡",
        "Nepal": "尼泊爾",
        "Afghanistan": "阿富汗",
        "China": "中國",
        "Chinese Taipei": "中華台北",
        "Hong Kong": "香港",
        "Macau": "澳門",
        "South Africa": "南非",
        "Angola": "安哥拉",
        "Zambia": "尚比亞",
        "Zimbabwe": "辛巴威",
        "Mozambique": "莫三比克",
        "Kenya": "肯亞",
        "Ethiopia": "衣索比亞",
        "Tanzania": "坦尚尼亞",
        "Uganda": "烏干達",
        "DR Congo": "剛果民主共和國",
        "Congo": "剛果",
        "Mali": "馬利",
        "Burkina Faso": "布吉納法索",
        "Niger": "尼日",
        "Mauritania": "茅利塔尼亞",
        "Guinea": "幾內亞",
        "Benin": "貝南",
        "Togo": "多哥",
        "Liberia": "賴比瑞亞",
        "Sierra Leone": "獅子山",
        "Guinea-Bissau": "幾內亞比索",
        "Gambia": "甘比亞",
        "Cape Verde": "維德角",
        "São Tomé and Príncipe": "聖多美普林西比",
        "Equatorial Guinea": "赤道幾內亞",
        "Gabon": "加彭",
        "Central African Republic": "中非共和國",
        "Chad": "查德",
        "South Sudan": "南蘇丹",
        "Sudan": "蘇丹",
        "Eritrea": "厄利垂亞",
        "Djibouti": "吉布地",
        "Somalia": "索馬利亞",
        "Rwanda": "盧安達",
        "Burundi": "蒲隆地",
        "Malawi": "馬拉威",
        "Lesotho": "賴索托",
        "Eswatini": "史瓦帝尼",
        "Botswana": "波札那",
        "Namibia": "納米比亞",
        "Madagascar": "馬達加斯加",
        "Comoros": "葛摩",
        "Seychelles": "塞席爾",
        "Mauritius": "模里西斯"
    ]
    
    static func getChineseName(for englishName: String) -> String {
        return mapping[englishName] ?? englishName
    }
}